### ISSUE TITLE
Achieve Home-Test Goals

### ISSUE THREAD

**Issue by codekeyz** [Rexfordasamoah51/AcheiveTest#1]
## Tasks

- [x] View Assets from CoinCap
- [x] Add Support for Searching Assets

- [x] For each Asset, you're to display the `name`, `priceUsd` & `marketCapUsd` using a ListTile.
- [x] Load More Assets when Assets Lists is Scrolled Downwards

- [x] Add Tests for Core Components

**Comment by codekeyz** [comment]
@Rexfordasamoah51  I've added the tasks you're to complete. Do tick them off as you push your code. Good luck 🚀

**Comment by rexthecoder** [comment]
Noted

**Comment by rexthecoder** [comment]
@codekeyz the API has a rate limit therefore, the test pass and fail sometimes.  
can just implement mock data and do widget testing?

**Comment by rexthecoder** [comment]
@codekeyz any feedback on the submission.
